pub const ERROR_PLAYER_ALREADY_EXIST: u32 = 1;
pub const ERROR_PLAYER_NOT_EXIST: u32 = 2;
pub const ERROR_NOT_SELECTED_PLAYER: u32 = 3;
pub const SELECTED_PLAYER_NOT_EXIST: u32 = 4;
pub const PLAYER_NOT_ENOUGH_BALANCE: u32 = 8;
pub const INVALID_NUGGET_INDEX: u32 = 9;
pub const NOTHING_TO_COLLECT: u32 = 10;


