pub const ERROR_PLAYER_ALREADY_EXIST: u32 = 1;
pub const ERROR_PLAYER_NOT_EXIST: u32 = 2;
pub const ERROR_NOT_SELECTED_PLAYER: u32 = 3;
pub const SELECTED_PLAYER_NOT_EXIST: u32 = 4;
pub const ERROR_NUGGET_ATTRIBUTES_ALL_EXPLORED: u32 = 5;
pub const ERROR_BID_PRICE_INSUFFICIENT: u32 = 6;
pub const PLAYER_NOT_ENOUGH_INVENTORY: u32 = 7;
pub const PLAYER_NOT_ENOUGH_BALANCE: u32 = 8;
pub const INVALID_NUGGET_INDEX: u32 = 9;
pub const NOTHING_TO_COLLECT: u32 = 10;
pub const NUGGET_IN_USE: u32 = 11;
pub const ERROR_NO_BIDDER: u32 = 12;
pub const INVALID_MARKET_INDEX: u32 = 13;
pub const ERROR_NOT_LISTED: u32 = 14;
pub const INVALID_BIDDER: u32 = 15;


