pub const ERROR_PLAYER_ALREADY_EXIST: u32 = 1;
pub const ERROR_PLAYER_NOT_EXIST: u32 = 2;
pub const ERROR_NOT_SELECTED_PLAYER: u32 = 3;
pub const SELECTED_PLAYER_NOT_EXIST: u32 = 4;
pub const PLAYER_ACTION_NOT_FINISHED: u32 = 5;
pub const PLAYER_LOTTERY_EXPIRED: u32 = 6;
pub const PLAYER_LOTTERY_PROGRESS_NOT_FULL: u32 = 7;
pub const PLAYER_NOT_ENOUGH_TICKET: u32 = 8;
pub const INVALID_MEME_INDEX: u32 = 9;


